version: "3"

services:

  proxy:
    image: "traefik:v2.4"
    container_name: "proxy"
    command:
    - "--log.level=DEBUG"
    - "--providers.docker=true"
    - "--providers.docker.exposedbydefault=false"
    ports:
    - "80:80"
    volumes:
    - "/var/run/docker.sock:/var/run/docker.sock:ro"

  default:
    image: "traefik/whoami"
    labels:
    - "traefik.enable=true"
    - "traefik.port=80"
    - "traefik.http.routers.default.rule=Host(`localhost`)"
