version: "3"

services:

  proxy:
    image: "traefik:v2.4"
    container_name: "proxy"
    command:
    - "--log.level=DEBUG"
    - "--providers.docker=true"
    - "--providers.docker.exposedbydefault=false"
    ports:
    - "80:80"
    volumes:
    - "/var/run/docker.sock:/var/run/docker.sock:ro"

  jobmanager:
    image: "flink:1.11.3"
    container_name: "jobmanager"
    environment:
      FLINK_PROPERTIES: "jobmanager.rpc.address: jobmanager"
    command:
    - "jobmanager"
    ports:
    - "8081"
